#!/bin/sh

echo "$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]%"

#Click:
case $BUTTON in
	1) 	setsid "$TERMINAL" -i -g=120x50-7 -z 14 -e htop;;
	2) 	setsid "$TERMINAL" -e vim ~/Programs/suckless/dwmblocks/bar-scripts/cpustatus;;
	3) 	kill "$(ps -ef ww | grep htop | grep st | grep -o '[0-9]\{4,6\}' | sed -n '1p')";;

esac

