#!/bin/sh

sudo pacman -Sy > /dev/null 2>&1
echo "包:$(pacman -Qu | wc -l)"

#Click:
case $BUTTON in
	1) 	setsid "$TERMINAL" -i -g=80x12-7 -z 16 -e sudo pacman -Syu;;
	2) 	setsid "$TERMINAL" -e vim ~/Programs/suckless/dwmblocks/bar-scripts/pacman-updates;;

esac

