#!/bin/sh
#Displays current audio status

volume_full=$(pulseaudio-ctl full-status)
read -a strarr <<< "$volume_full"
volume_return="音${strarr[0]}%"

case ${strarr[1]} in
	yes) volume_return="${volume_return} "	;;
esac
case ${strarr[2]} in
	yes) volume_return="${volume_return} " ;;
esac

echo $volume_return
