#!/bin/bash

#Gets weather data from pre-downloaded file

#Get current temperature:
current="  現$(sed '1,6!d' ~/.local/share/weather-report.txt | grep "°C" | grep -o "m\-\?+\?[0-9]\+" | tr -d 'm''\+' | tr '\n' ' ' | sed 's/ .*//')°"
#Get daily min and max:
temperature_list="$(sed '13!d' ~/.local/share/weather-report.txt | sed 's/([^ ]*)//g'| grep -o "m\-\?+\?[0-9]\+" | sed 's/m//g;s/+//g' | sort -n | tr '\n' ' ')"
read -a temperature_array <<< "$temperature_list"
min_max="低${temperature_array[0]}° 高${temperature_array[3]}°"
							
#Get max percipitation %:
percip="雨$(sed '16!d' ~/.local/share/weather-report.txt | grep -o "[0-9]\+%" | tr -d '%' | sort -n | tr '\n' ' ' | grep -o '[0-9]\+\s$' | tr -d ' ')%"

echo $current $min_max $percip | tr -d ' '
											

#Click:
case $BUTTON in
	1) 	curl wttr.in > ./ref/wttr-out && setsid "$TERMINAL" -i -g=80x12-7 -z 14 -e less ./ref/wttr-out;;
	2) 	setsid "$TERMINAL" -e vim ~/Programs/suckless/dwmblocks/bar-scripts/sound-display;;
	3) 	kill "$(ps -ef ww | grep pulsemixer | grep st | grep -o '[0-9]\{4,6\}' | sed -n '1p')";;

esac
